apiVersion: 3
dataDisplay:
  textFormats:
    layout-orig-full: 
      method: layoutRich
      style:  orig
docs:
  docBase: '{docRoot}/bhsa'
  docExt: ''
  docPage: ''
  docRoot: https://etcbc.github.io
  featurePage: 0_home
interfaceDefaults: {}
provenanceSpec:
  corpus: Copenhagen Ugarit Corpus
  version: '0.1'
writing: hbo
typeDisplay:
  verse:
    label: '{line}'
    template: '{line}'
    verselike: true
