apiVersion: 3
dataDisplay:
  textFormats:
    text-orig-full: 
      method: layoutTrans
      style:  trans
    text-orig-unicode:
      method: layoutUnicode
      style: orig
docs:
  docPage: about
  featureBase: '{docBase}/transcription.md'
  featurePage: transcription
interfaceDefaults: {}
provenanceSpec:
  corpus: Copenhagen Ugarit Corpus
  version: '0.1.4'
writing: uga
typeDisplay:
  line:
    label: '{line}'
    template: '{line}'
    verselike: true